// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSR94y6fXQ09jkdgFuwU0SJIzoTG8W0MU',
    appId: '1:170884781540:web:d3a5e8be8a4dd5a0d3a3f1',
    messagingSenderId: '170884781540',
    projectId: 'app-unicv',
    authDomain: 'app-unicv.firebaseapp.com',
    storageBucket: 'app-unicv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCCv6ixuAv9K-TuDHEdM0Ox9L9ZGyhdcA',
    appId: '1:170884781540:android:cec9aef5b3da5273d3a3f1',
    messagingSenderId: '170884781540',
    projectId: 'app-unicv',
    storageBucket: 'app-unicv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBttHn6qS4zyeZ3_gvKHo3GKGEg7QO8H2c',
    appId: '1:170884781540:ios:23341e4a7c40195ad3a3f1',
    messagingSenderId: '170884781540',
    projectId: 'app-unicv',
    storageBucket: 'app-unicv.appspot.com',
    iosBundleId: 'com.example.appUnicv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBttHn6qS4zyeZ3_gvKHo3GKGEg7QO8H2c',
    appId: '1:170884781540:ios:23341e4a7c40195ad3a3f1',
    messagingSenderId: '170884781540',
    projectId: 'app-unicv',
    storageBucket: 'app-unicv.appspot.com',
    iosBundleId: 'com.example.appUnicv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSR94y6fXQ09jkdgFuwU0SJIzoTG8W0MU',
    appId: '1:170884781540:web:405861f83b3fec6fd3a3f1',
    messagingSenderId: '170884781540',
    projectId: 'app-unicv',
    authDomain: 'app-unicv.firebaseapp.com',
    storageBucket: 'app-unicv.appspot.com',
  );

}